<div class="pheader clearfix">体检卡购买记录</div>
<div class="pbody clearfix">
	<ul class="nav nav-tabs">
	    <li role="presentation" <?php echo $aParam['type'] == 0 ? 'class="active"' : '' ?>><a href="<?php echo $aParam['type'] == 0  ? 'javascript:;' : '/admin/order/refund/type/0.html' ?>">未处理</a></li>
	    <li role="presentation" <?php echo $aParam['type'] == 1 ? 'class="active"' : '' ?>><a href="<?php echo $aParam['type'] == 1 ? 'javascript:;' : '/admin/order/refund/type/1.html' ?>">已处理</a></li>
	</ul>
</div>
<div class="pbody clearfix">
    <form class="form-inline search-form" role="form" method="post" id="myform" action="/admin/order/refund/">
        <input type="hidden" name="type" value="<?php echo intval($aParam['type']);?>" />
        <div class="row">
            <div class="form-group col-sm-3">
                <label style="width: 70px">姓名：</label>
                <input type="text" value="<?php echo !empty($aParam['sRealName']) ? $aParam['sRealName'] : '' ?>"
                       class="form-control" name="sRealName" style="width: 100px">
            </div>
            <div class="form-group col-sm-3">
                <label style="width: 70px">身份证：</label>
                <input type="text" value="<?php echo !empty($aParam['sIdentityCard']) ? $aParam['sIdentityCard'] : '' ?>"
                       class="form-control" name="sIdentityCard" style="width: 100px">
            </div>
            <div class="form-group col-sm-3">
                <label style="width: 100px">订单流水号：</label>
                <input type="text" value="<?php echo !empty($aParam['sOrderCode']) ? $aParam['sOrderCode'] : '' ?>"
                       class="form-control" name="sOrderCode" style="width: 100px">
            </div>
            
            <div class="form-group">
                <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
                <button class="btn btn-primary" onclick="location.href='/admin/order/refundexport?type=<?php echo empty($type) ? 0 : 1;?>';return false;">导出</button>
            </div>
        </div>
    </form>
    <hr>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="text-center">员工姓名</th>
            <th class="text-center">身份证</th>
            <th class="text-center">订单流水号</th>
            <th class="text-center">退费金额</th>
            <th class="text-center">第三方订单号</th>
            <th class="text-center">申请时间</th>
            <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php if (!empty($aData['aList'])) {
            foreach ($aData['aList'] as $aRefund) { ?>
                <tr>
                    <td class="text-center"><?php echo !empty($aRefund['sRealName']) ? $aRefund['sRealName'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aRefund['sIdentityCard']) ? $aRefund['sIdentityCard'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aRefund['sOrderCode']) ? $aRefund['sOrderCode'] : '' ?></td>
                    <td class="text-center"><?php echo ($aParam['type'] == 0) ? $aRefund['refund'] : $aRefund['iRefund']; ?></td>
                    <td class="text-center"><?php echo !empty($aRefund['sPayOrderID']) ? $aRefund['sPayOrderID'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aRefund['iCanncalReserveTime']) ? date("Y-m-d", $aRefund['iCanncalReserveTime']) : '' ?></td>
                    <td class="text-center">
                        <a  href="javascript:checkrefund(<?php echo $aRefund['iAutoID'] ?>);" title="处理"><i
                                class="fa fa-pencil fa-large"></i></a>
                    </td>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>
    <?php echo !empty($aData['aPager']) ? $aData['aPager'] : '' ?>
</div>
<script type="text/javascript">
    function checkrefund(id){
        var url = '/admin/order/refundcheck';
        var data = {icpID: id};

        if (confirm("您确认处理吗？")) {
            $.post(url, data, function (ret) {
                if (ret.status) {
                    alert(ret.data);
                    location.reload();
                }else {
                    alert(ret.data);
                }
            }, 'json');
        }
    }
</script>